workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS Simulator App
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - armansaheb@gmail.com
